export const DASHBOARD_PERMISSIONS = {
  VIEW: 'DASHBOARD_VIEW',
  STATISTICS_VIEW: 'DASHBOARD_STATISTICS_VIEW',
} as const;

export const PRODUCT_PERMISSIONS = {
  VIEW: 'PRODUCT_VIEW',
  CREATE: 'PRODUCT_CREATE',
  UPDATE: 'PRODUCT_UPDATE',
  IMAGE_UPLOAD: 'PRODUCT_IMAGE_UPLOAD',
} as const;

export const CATEGORY_PERMISSIONS = {
  VIEW: 'CATEGORY_VIEW',
  CREATE: 'CATEGORY_CREATE',
  UPDATE: 'CATEGORY_UPDATE',
} as const;

export const ORDER_PERMISSIONS = {
  VIEW: 'ORDER_VIEW',
  STATUS_UPDATE: 'ORDER_STATUS_UPDATE',
  STATISTICS_VIEW: 'ORDER_STATISTICS_VIEW',
} as const;

export const DINE_IN_PERMISSIONS = {
  ORDER_VIEW: 'DINE_IN_ORDER_VIEW',
  ORDER_CREATE: 'DINE_IN_ORDER_CREATE',
  TABLE_MANAGE: 'DINE_IN_TABLE_MANAGE',
  KITCHEN_UPDATE: 'DINE_IN_KITCHEN_UPDATE',
  PAYMENT_CONFIRM: 'DINE_IN_PAYMENT_CONFIRM',
} as const;

export const CHAT_PERMISSIONS = {
  VIEW: 'CHAT_VIEW',
  REPLY_SEND: 'CHAT_REPLY_SEND',
  QUICK_REPLY_MANAGE: 'CHAT_QUICK_REPLY_MANAGE',
} as const;

export const STORE_POLICY_PERMISSIONS = {
  VIEW: 'STORE_POLICY_VIEW',
  UPDATE: 'STORE_POLICY_UPDATE',
} as const;

export const CART_ADD_ON_SETTING_PERMISSIONS = {
  VIEW: 'CART_ADD_ON_SETTING_VIEW',
  UPDATE: 'CART_ADD_ON_SETTING_UPDATE',
} as const;

export const NOTIFICATION_PERMISSIONS = {
  VIEW: 'NOTIFICATION_VIEW',
  CREATE: 'NOTIFICATION_CREATE',
  UPDATE: 'NOTIFICATION_UPDATE',
  SEND: 'NOTIFICATION_SEND',
} as const;

export const BILL_PERMISSIONS = {
  VIEW: 'BILL_VIEW',
  CREATE: 'BILL_CREATE',
  UPDATE: 'BILL_UPDATE',
  APPROVE: 'BILL_APPROVE',
} as const;

export const USER_PERMISSIONS = {
  ACCESS_VIEW: 'USER_ACCESS_VIEW',
  ACCESS_MANAGE: 'USER_ACCESS_MANAGE',
} as const;

export const ACCOUNT_PERMISSIONS = {
  PROFILE_UPDATE: 'ADMIN_PROFILE_UPDATE',
  PASSWORD_CHANGE: 'ADMIN_PASSWORD_CHANGE',
} as const;

export const PERMISSIONS = {
  ...DASHBOARD_PERMISSIONS,
  ...PRODUCT_PERMISSIONS,
  ...CATEGORY_PERMISSIONS,
  ...ORDER_PERMISSIONS,
  ...DINE_IN_PERMISSIONS,
  ...CHAT_PERMISSIONS,
  ...STORE_POLICY_PERMISSIONS,
  ...CART_ADD_ON_SETTING_PERMISSIONS,
  ...NOTIFICATION_PERMISSIONS,
  ...BILL_PERMISSIONS,
  ...USER_PERMISSIONS,
  ...ACCOUNT_PERMISSIONS,
} as const;

export type PermissionValue = string;
